Add error output

diff --git a/run-pipeline b/run-pipeline
--- a/run-pipeline
+++ b/run-pipeline
@@ -1,3 +1,4 @@
 #!/bin/bash
 
 echo "Some output"
+echo "Some error output" 1>&2
